---
title: "flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup}
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```


```{r tidy data}
airbnb = 
  nyc_airbnb %>% 
  filter(!is.na(review_scores_location)) %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(boro = neighbourhood_group, neighbourhood, rating, price, room_type,
         latitude, longitude)
```



Column {data-width=650}
-----------------------------------------------------------------------

### Rating proportions by boro

```{r rating by boro plot}
bar_plot = airbnb %>% 
  mutate(rating = as.character(rating)) %>%
  group_by(boro, rating) %>%
  summarize(count = n()) %>%
  group_by(boro) %>% 
  mutate(sum = sum(count)) %>% 
  mutate(proportion = count/sum) %>%
  ggplot(aes(x = boro, y = proportion, fill = rating)) + 
  geom_bar(width = 0.9, position = position_dodge(width=1.0), stat="identity") +
  theme_bw()

ggplotly(bar_plot)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Price by rating in Staten Island

```{r price by rating plot}
# plotly gave me a y axis title, but I had to manually define the x axis title
x <- list(
  title = "rating"
)

airbnb %>% 
  filter(boro == "Staten Island") %>%
  mutate(rating = as.character(rating)) %>% 
  plot_ly(y = ~price, color = ~rating, type = "box") %>% 
  layout(xaxis = x) # set x axis title, refering to x defined above

```

### Airbnbs in Staten Island

```{r staten island airbnb plot}
airbnb %>% 
  filter(boro == "Staten Island") %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price,
          text = ~text_label)
```


